botOwner = "yournamehere"
botNick = "botnamehere"
botOAuth = "oauthtokenhere"
helloMessage = "Hello! GoldenrodNostalgia is here and ready for business. (Streamer - remember you can use !goldenrodctl on/off.)"
byeMessage = "The stream is over so I'm out for now too, see you later."
doSayHello = True
twitchModsMsg = "The moderators of this room are: "
cmdChar = "!"
cmdCharLen = len(cmdChar)
startingBalance = 20
currencyName = "point"
currencyPlural = "points"
gameCooldown = 45
contestChoiceWeightings = [["guessnumber", 5], ["hangman", 70], ["trivia", 25]]
contestInterval = 180
contestDuration = 90
guessMinNumber = 1
guessMaxNumber = 100
guessPrize = 50
guessPrizeConsolation = 10
hangmanPrizeBase = 75
hangmanPrizeLetterReduction = 3
triviaPrizes = [25, 50, 100]
triviaDifficulties = ["easy", "medium", "hard"]
triviaPrizeReducFirst = 15
triviaPrizeReducSecond = 30
handoutScriptBan = 3600
showCooldowns = True
duelRequestExpiry = 3600