# create database for goldenrodgames
import datetime, time
import config

def create(conn, cursor):
    cursor.execute("""CREATE TABLE "users" ("twitchname" VARCHAR PRIMARY KEY  NOT NULL ,"balance" INTEGER NOT NULL  DEFAULT (0) ,"last_activity" DATETIME DEFAULT (CURRENT_DATE) ,"last_game" INTEGER DEFAULT (0) , "handouts" INTEGER NOT NULL  DEFAULT 0, "coins_won" INTEGER NOT NULL  DEFAULT 0, "coins_lost" INTEGER NOT NULL  DEFAULT 0, "highest_handout" INTEGER NOT NULL  DEFAULT 0, "contests_won" INTEGER NOT NULL  DEFAULT 0, "highest_balance" INTEGER NOT NULL  DEFAULT 0, "handout_ban" INTEGER NOT NULL  DEFAULT 0, "coin_profit" INTEGER NOT NULL  DEFAULT 0)""")
    cursor.execute("""CREATE TABLE "coinflips" ("twitchname" VARCHAR NOT NULL ,"amount" INTEGER NOT NULL  DEFAULT (0) ,"yoloflip" BOOL NOT NULL  DEFAULT (0) ,"winner" BOOL NOT NULL ,"whenHappened" DATETIME, "channel" VARCHAR)""")
    cursor.execute("""CREATE TABLE "slots" ("twitchname" VARCHAR NOT NULL , "reelOne" VARCHAR NOT NULL , "reelTwo" VARCHAR NOT NULL , "reelThree" VARCHAR NOT NULL , "winner" BOOL NOT NULL , "balChange" INTEGER NOT NULL , "whenHappened" DATETIME NOT NULL , "channel" VARCHAR)""")
    cursor.execute("""CREATE TABLE "donations" ("fromPlayer" VARCHAR NOT NULL , "toPlayer" VARCHAR NOT NULL , "amount" INTEGER NOT NULL , "whenHappened" DATETIME NOT NULL , "channel" VARCHAR)""")
    cursor.execute("""CREATE TABLE "taxes" ("twitchname" VARCHAR NOT NULL , "amount" INTEGER NOT NULL , "whenHappened" DATETIME NOT NULL , "channel" VARCHAR)""")
    cursor.execute("""CREATE TABLE "charity" ("twitchname" VARCHAR NOT NULL , "amount" INTEGER NOT NULL , "whenHappened" DATETIME NOT NULL , "channel" VARCHAR)""")
    cursor.execute("""CREATE TABLE "slotspool" ("slotspool" INTEGER NOT NULL  DEFAULT 50, "last_change" DATETIME NOT NULL , "last_winner" DATETIME NOT NULL )""")
    cursor.execute("""CREATE TABLE "alts" ("twitchname" VARCHAR PRIMARY KEY  NOT NULL , "whenHappened" DATETIME)""")
    cursor.execute("""CREATE TABLE "contestwins" ("twitchname" VARCHAR NOT NULL , "gameid" VARCHAR NOT NULL , "answer" VARCHAR NOT NULL , "reward" INTEGER NOT NULL , "whenHappened" DATETIME NOT NULL , "channel" VARCHAR)""")
    cursor.execute("""CREATE TABLE "trivia_questions" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "question" TEXT NOT NULL  UNIQUE , "difficulty" INTEGER NOT NULL  DEFAULT 1, "whenAdded" DATETIME NOT NULL , "question_grouping" INTEGER NOT NULL  DEFAULT 0, "used_in_cycle" BOOL NOT NULL  DEFAULT 0)""")
    cursor.execute("""CREATE TABLE "trivia_answers" ("question_id" INTEGER NOT NULL , "answer" TEXT NOT NULL )""")
    cursor.execute("""CREATE TABLE "handouts" ("twitchname" VARCHAR NOT NULL ,"amount" INTEGER NOT NULL  DEFAULT (0) ,"whenHappened" TIMESTAMP DEFAULT (null) , "channel" VARCHAR)""")
    cursor.execute("""CREATE TABLE "hangman_words" ("id" INTEGER PRIMARY KEY AUTOINCREMENT , "word" VARCHAR NOT NULL , "whenAdded" DATETIME NOT NULL , "used_in_cycle" BOOL NOT NULL  DEFAULT 0)""")
    cursor.execute("""CREATE TABLE "trivia_winners" ("twitchname" VARCHAR NOT NULL , "question_id" INTEGER NOT NULL , "timeTaken" INTEGER NOT NULL , "reward" INTEGER NOT NULL , "whenHappened" DATETIME NOT NULL , "channel" VARCHAR)""")
    cursor.execute("""CREATE INDEX "trivia_winners_lookup" ON "trivia_winners" ("twitchname" ASC, "question_id" ASC)""")
    cursor.execute("""CREATE TABLE "duel_requests" ("from_user" VARCHAR NOT NULL , "to_user" VARCHAR NOT NULL , "amount" INTEGER NOT NULL , "expiry" INTEGER NOT NULL , "whenHappened" DATETIME NOT NULL , "channel" VARCHAR)""")
    cursor.execute("""CREATE TABLE "duel_results" ("from_user" VARCHAR NOT NULL , "to_user" VARCHAR NOT NULL , "roll1" INTEGER NOT NULL , "roll2" INTEGER NOT NULL , "amount" INTEGER NOT NULL , "winner" VARCHAR, "whenHappened" DATETIME NOT NULL , "channel" VARCHAR)""")
    cursor.execute("""CREATE TABLE "channels" ("channel" VARCHAR PRIMARY KEY  NOT NULL ,"commandsEnabled" BOOL NOT NULL  DEFAULT (1) ,"lastChange" DATETIME NOT NULL ,"joinIfLive" BOOL NOT NULL  DEFAULT (1) )""")
    cursor.execute("""CREATE INDEX charity_twitch ON charity (twitchname)""")
    cursor.execute("""CREATE INDEX coinflips_twitch ON coinflips (twitchname)""")
    cursor.execute("""CREATE INDEX contestwins_twitch ON contestwins (twitchname)""")
    cursor.execute("""CREATE INDEX donations_from ON donations (fromPlayer)""")
    cursor.execute("""CREATE INDEX donations_to ON donations (toPlayer)""")
    cursor.execute("""CREATE INDEX duel_requests_from ON duel_requests (from_user)""")
    cursor.execute("""CREATE INDEX duel_requests_to ON duel_requests (to_user)""")
    cursor.execute("""CREATE INDEX duel_results_from ON duel_results (from_user)""")
    cursor.execute("""CREATE INDEX duel_results_to ON duel_results (to_user)""")
    cursor.execute("""CREATE INDEX handouts_twitch ON handouts (twitchname)""")
    cursor.execute("""CREATE INDEX slots_twitch ON slots (twitchname)""")
    cursor.execute("""CREATE INDEX taxes_twitch ON taxes (twitchname)""")
    cursor.execute("""CREATE INDEX trivia_answers_question ON trivia_answers (question_id)""")
    cursor.execute("""CREATE INDEX trivia_winners_twitch ON trivia_winners (twitchname)""")
    cursor.execute("""CREATE INDEX trivia_winners_question ON trivia_winners (question_id)""")
    cursor.execute("""CREATE INDEX "charity_channel" ON "charity" ("channel" ASC)""")
    cursor.execute("""CREATE INDEX "coinflips_channel" ON "coinflips" ("channel" ASC)""")
    cursor.execute("""CREATE INDEX "contestwins_channel" ON "contestwins" ("channel" ASC)""")
    cursor.execute("""CREATE INDEX "donations_channel" ON "donations" ("channel" ASC)""")
    cursor.execute("""CREATE INDEX "duel_requests_channel" ON "duel_requests" ("channel" ASC)""")
    cursor.execute("""CREATE INDEX "duel_results_channel" ON "duel_results" ("channel" ASC)""")
    cursor.execute("""CREATE INDEX "handouts_channel" ON "handouts" ("channel" ASC)""")
    cursor.execute("""CREATE INDEX "slots_channel" ON "slots" ("channel" ASC)""")
    cursor.execute("""CREATE INDEX "taxes_channel" ON "taxes" ("channel" ASC)""")
    cursor.execute("""CREATE INDEX "trivia_winners_channel" ON "trivia_winners" ("channel" ASC)""")
    conn.commit()
    cursor.execute("""INSERT INTO slotspool (slotspool, last_change, last_winner) VALUES(?, ?, ?)""", (100, int(time.time()), int(time.time())))
    cursor.execute("""INSERT INTO channels (channel, commandsEnabled, lastChange, joinIfLive) VALUES(?, ?, ?, ?)""", (config.botNick, False, int(time.time()), False))
    cursor.execute("""INSERT INTO trivia_questions (question, difficulty, whenAdded, question_grouping, used_in_cycle) VALUES(?, ?, ?, ?, ?)""", ("Sample question", 0, int(time.time()), 1, 0))
    cursor.execute("""INSERT INTO trivia_answers (question_id, answer) VALUES(?, ?)""", (1, "Sample answer"))
    cursor.execute("""INSERT INTO hangman_words (word, whenAdded, used_in_cycle) VALUES(?, ?, ?)""", ("test", int(time.time()), 0))
    conn.commit()